# Generated by Django 5.0.1 on 2024-02-06 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.BigIntegerField(unique=True)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('prof_pic', models.ImageField(null=True, upload_to='media/photos')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.area')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.city'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.BigIntegerField(unique=True)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('prof_pic', models.ImageField(upload_to='media/photos')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.area')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('price', models.BigIntegerField(null=True)),
                ('desc', models.TextField(null=True)),
                ('bedroom', models.IntegerField(default=0, null=True)),
                ('hall', models.IntegerField(default=0, null=True)),
                ('bathroom', models.IntegerField(default=0, null=True)),
                ('kitchen', models.IntegerField(default=0, null=True)),
                ('balcony', models.IntegerField(default=0, null=True)),
                ('floor', models.IntegerField(default=0, null=True)),
                ('total_floor', models.IntegerField(default=0, null=True)),
                ('address', models.TextField()),
                ('docs', models.ImageField(null=True, upload_to='media/docs')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(null=True)),
                ('rate', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.buyer')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/property')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.property')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('mobile_no', models.BigIntegerField(null=True, unique=True)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('prof_pic', models.ImageField(default='', upload_to='media/photos')),
                ('document', models.ImageField(null=True, upload_to='media/docs')),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.area')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.seller'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(null=True)),
                ('pay_amount', models.BigIntegerField(null=True)),
                ('transaction_id', models.CharField(max_length=70, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.buyer')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.property')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Seller_Ac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('acc_no', models.CharField(max_length=30, null=True, unique=True)),
                ('ifsc_code', models.CharField(max_length=20, null=True)),
                ('bank_name', models.CharField(max_length=30, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.seller')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.state'),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('desc', models.TextField(null=True)),
                ('verification_date', models.DateField(null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.property')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.buyer')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.property')),
            ],
        ),
    ]
