# Generated by Django 5.0.1 on 2024-02-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_area_options_alter_buyer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'State'},
        ),
    ]
