# Generated by Django 5.0.1 on 2024-02-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_buyer_pincode_seller_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='address',
        ),
    ]
