# Generated by Django 5.0.1 on 2024-02-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_buyer_mobile_no_alter_employee_mobile_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='area_name',
        ),
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='area',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='area',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='area',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
